---
name: nginx

releases:
- name: nginx
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nginx
  instances: 1
  stemcell: default
  vm_type: default
  azs: [z1]
  persistent_disk_type: default
  networks:
  - name: default
  jobs:
  - name: nginx
    release: nginx
    properties:
      nginx_worker_processes: 1
      nginx_worker_connections: 1024
      nginx_servers:
      - server_name: localtest.local
        docroot: /var/vcap/store/nginx/www/document_root
        port: 80
        index: "index.php index.html index.htm"
        access_log: /var/vcap/sys/log/nginx/access.log
        error_log: /var/vcap/sys/log/nginx/error.log
        custom_data: |
                     location / {
                         try_files $uri $uri/ =404;
                     }
                     location ~ \.php$ {
                         try_files $uri =404;
                         fastcgi_split_path_info ^(.+\.php)(/.+)$;
                         fastcgi_pass 127.0.0.1:9000;
                         fastcgi_index index.php;
                         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                         include fastcgi_params;
                     }


update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
