---

groups:
  - name: '((pipeline.name))'
    jobs:
      - blobs
      - test-release
      - bump-rc
      - promote-release
      - bump-major
      - bump-minor
  - name: blobs
    jobs:
      - blobs
  - name: test
    jobs:
      - test-release
      - bump-rc
      - bump-major
      - bump-minor
  - name: promote
    jobs:
      - promote-release

jobs:
  - name: blobs
    public: true
    serial: true
    plan:
    - do:
      - aggregate:
        - get: pcre-external
          version: ((blob.pcre.version))
        - get: zlib-external
          version: ((blob.zlib.version))
          params:
            include_source_tarball: true
        - get: nginx-external
          version: ((blob.nginx.version))
          params:
            include_source_tarball: true
        - get: bosh-release
      - task: add-upload-blob
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: oaktondigital/bosh-cli}
          inputs:
            - { name: nginx-external }
            - { name: pcre-external }
            - { name: zlib-external }
            - { name: bosh-release }
          outputs:
            - { name: pushgit }
            - { name: message }
          run:
            path: ./bosh-release/ci/scripts/addblob
          params:
            PIPELINE_NAME: ((pipeline.name))
            AWS_BUCKET: ((blob.nginx.aws.bucket))
            AWS_ACCESS_KEY:       ((blob.nginx.aws.access_key))
            AWS_SECRET_KEY:       ((blob.nginx.aws.secret_key))
      - name: upload-git
        put: bosh-release
        params:
          repository: pushgit/bosh-release
      on_success:
        put: notify
        params:
          channel: ((slack.channel))
          icon_url: ((slack.icon_success))
          text_file: message/body
          username: ((slack.successname))
#          text: 'Successfully added new Nginx blob for ((pipeline.name))'
      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failed to add new Nginx blob for ((pipeline.name))'

  - name: test-release
    public: true
    serial: true
    plan:
    - do:
      - aggregate:
        - get: bosh-release
          trigger: true
        - get: version
        - get: bosh-stemcell
          version: ((bosh.stemcell_version))
          trigger: true
      - task: test-release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: oaktondigital/bosh-cli}
          inputs:
            - { name: bosh-release }
            - { name: version }
            - { name: bosh-stemcell }
          run:
            path: ./bosh-release/ci/scripts/testrelease
            args: []
          params:
            VERSION_FROM: version/number
            BOSH_TARGET:     ((bosh.target))
            BOSH_USERNAME:   ((bosh.username))
            BOSH_PASSWORD:   ((bosh.password))
            BOSH_DEPLOYMENT: ((bosh.deployment))
            BOSH_CA_CERT: ((bosh.ca_cert))
#            TEST_ERRAND: ((bosh.test-errand))
      on_success:
        put: notify
        params:
          channe: ((slack.channel))
          icon_url: ((slack.icon_success))
          username: ((slack.successname))
          text: 'Successful test of release for ((pipeline.name))'
      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failure of test-release for ((pipeline.name))'

  - name: bump-rc
    public: true
    plan:
    - do:
      - aggregate:
          - { get: bosh-release,     trigger: true,  passed: [test-release] }
          - { get: version, trigger: true, params: {pre: rc} }
      - put: version
        params: {file: version/number}
      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failed to bump RC version for ((pipeline.name))'

  - name: bump-minor
    public: true
    plan:
    - do:
      - { get: version, trigger: false, params: {bump: minor} }
      - { put: version,                 params: {file: version/number} }
      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failure to bump minor version for ((pipeline.name))'

  - name: bump-major
    public: true
    plan:
    - do:
      - { get: version, trigger: false, params: {bump: major} }
      - { put: version,                 params: {file: version/number} }
      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failure to bump major version for ((pipeline.name))'

  - name: promote-release
    public: true
    serial: true
    plan:
    - do:
      - name: inputs
        aggregate:
          - { get: version, passed: [bump-rc], params: {bump: final} }
          - { get: bosh-release,     passed: [bump-rc] }
      - name: release
        task: release
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: oaktondigital/bosh-cli}
          inputs:
            - name: version
            - name: bosh-release
          outputs:
            - name: gh
            - name: pushme
          run:
            path: ./bosh-release/ci/scripts/cutrelease
            args: []
          params:
            VERSION_FROM: version/number
            RELEASE_NAME: "((release)) BOSH Release"
            RELEASE_NAME2: ((release))
            GITHUB_OWNER: ((github.owner))
            GITHUB_REPO: ((github.repo))
            BRANCH:       ((github.branch))
            BOSH_TARGET:     ((bosh.target))
            BOSH_USERNAME:   ((bosh.username))
            BOSH_PASSWORD:   ((bosh.password))
            BOSH_DEPLOYMENT: ((bosh.deployment))
            BOSH_CA_CERT: ((bosh.ca_cert))
            AWS_BUCKET: ((aws.bucket))
            AWS_ACCESS_KEY:       ((aws.access_key))
            AWS_SECRET_KEY:       ((aws.secret_key))

      - name: upload-git
        put: bosh-release
        params:
          rebase: true
          repository: pushme/bosh-release
      - name: tarball
        put: blobstore
        params:
          file:  "gh/artifacts/((name))-*.tgz"
      - name: github-release
        put: github-release
        params:
          name:   gh/name
          tag:    gh/tag
          body:   gh/notes.md
          globs: [gh/artifacts/*]
      - name: version-bump
        put: version
        params:
          bump: patch
      on_success:
        put: notify
        params:
          channel: ((slack.channel))
          icon_url: ((slack.icon_success))
          username: ((slack.successname))
#          text: '((pipeline.name)): promote-release success'
          text_file: gh/notification

      on_failure:
        put: notify
        params:
          channel:  ((slack.channel))
          icon_url: ((slack.icon_fail))
          username: ((slack.failname))
          text:    'Failed to promote release of job for ((pipeline.name))'

resource_types:
  - name: bosh-deployment
    type: docker-image
    source:
      repository: cloudfoundry/bosh-deployment-resource

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

  - name: git-release-tags
    type: docker-image
    source:
      repository: shreddedbacon/git-release-tags

  - name: http-directory-index
    type: docker-image
    source:
      repository: shreddedbacon/http-directory-index

resources:
  - name: bosh-release
    type: git
    source:
      uri:         ((github.uri))
      branch:      ((github.branch))
      private_key: ((github.private_key))

  - name: version
    type: semver
    source :
      driver:            s3
      bucket:            ((aws.bucket))
      key:               version
      access_key_id:     ((aws.access_key))
      secret_access_key: ((aws.secret_key))
      initial_version:   ((initial_version))
      region_name: ((aws.region))
      endpoint: ((aws.endpoint))

  - name: notify
    type: slack-notification
    source:
      url: ((slack.webhook))

  - name: github-release
    type: github-release
    source:
      user:         ((github.owner))
      repository:   ((github.repo))
      access_token: ((github.access_token))

  - name: blobstore
    type: s3
    source:
      bucket:            ((aws.bucket))
      regexp:            "((name))-(.*).tgz"
      access_key_id:     ((aws.access_key))
      secret_access_key: ((aws.secret_key))
      region_name: ((aws.region))
      endpoint: ((aws.endpoint))

  - name: bosh-stemcell
    type: bosh-io-stemcell
    source:
      name: ((bosh.stemcell))
      #      name: bosh-warden-boshlite-ubuntu-trusty-go_agent


  - name: nginx-external
    type: git-release-tags
    source:
      owner: ((blob_git.nginx.owner))
      repo: ((blob_git.nginx.repo))
      token: ((blob_git.access_token))
      tag_prefix: ((blob_git.nginx.prefix))
      version_family: '1.12'

  - name: zlib-external
    type: git-release-tags
    source:
      owner: ((blob_git.zlib.owner))
      repo: ((blob_git.zlib.repo))
      token: ((blob_git.access_token))
      tag_prefix: ((blob_git.zlib.prefix))

  - name: pcre-external
    type: http-directory-index
    source:
      url: ((blob.pcre.url))
      file_prefix: ((blob.pcre.prefix))
      file_regex: "([0-9]+\\.)?([0-9]+)?"
      file_extension: .tar.gz
      file_reverse: false
